### ISSUE TITLE
@include forces that include file must always exist. 

### ISSUE THREAD

**Issue by kashiif** [STAH/grunt-preprocessor#2]
First of all thanks for this great plugin. This is my first of two issues that I have faced using grunt-preprocess. Although not sure whether I should report these in preprocess repo or here, I am reporting here but advise me otherwise.

Consider if I have used something like in my source file:

    // @ifdef WIDGETS
    // @include ../temp/widgets.inc
    // @endif

In my usecase, `widgets.inc` will only be generated conditionally but whenever `WIDGETS` is set in the task, `widgets.inc` does exist.

Problem arise when my task context does not set `WIDGETS` and hence no `widgets.inc` exists. The preprocess task will fail reporting that widgets.inc doesn't exist. My workaround for this has been to have an empty `widgets.inc` always and overwrite it when required.

As far as I have understood, this happens because `@include` is processed before `@ifdef`. (See `preprocess()` in `preprocess.js`). I don't know if it is there by design or for a reason but my opinion is since `@ifdef` is a block level directive, its body may contain other directives so it should be processed first.

**Comment by STAH** [comment]
Please open issue on https://github.com/nashdot/Preprocessor.js.
Grunt task is based on it.
