### ISSUE TITLE
Provide a way to @include a file relative to GruntFile.js

### ISSUE THREAD

**Issue by kashiif** [STAH/grunt-preprocessor#3]
Consider the case where files in multiple folders that are on different levels of hierarchy need to include same file. e.g. if the files in any folder under `<dist>` need to include license.txt ,

    |-- <grunt-includes>
    |               |-- license.txt
    |
    |-- <dist>
        |-- <public>
        |         |------- <js>
        |         |------- <css>
        |-- <admin> 

they must do so using path relative to their own location. Now, if a file is moved from  public/js to admin, the preprocess task would fail because it would not be able to include license.txt unless the path used in directive is updated.

It would be more convenient in this case to allow including a file using a path relative to GruntFile.js. I like the way [htmlrefs](https://github.com/tactivos/grunt-htmlrefs) addresses this problem. It lets you define includes on task level like:

    includes: {
        'jquery-cdn': './grunt-includes/jquery-cdn.inc',
        'jquery-ui-cdn': './grunt-includes/jquery-ui-cdn.inc'
    },
  
and then I can include the file using its canonical name:

    // @build:include jquery-cdn 

This is easy to maintain even in the case if jquery-cdn.inc location is changed.

**Comment by STAH** [comment]
Please open issue on https://github.com/nashdot/Preprocessor.js.
Grunt task is based on it.
