### ISSUE TITLE
put will fail and provides vulns

### ISSUE THREAD

**Issue by wzrdtales** [STAH/grunt-preprocessor#8]
Hello guys,

today I had to switch from my Linux machine to a windows 7 business one -.-

I hate it...
But currently there happend something funny.

"Syntax error: unexpected token !"

The root of the whole evil is this line:
```javascript
_.extend(context, process.env);
```

On my current System it returns as first value the following:
```javascript
"!::" : "::/"
```

Strange enough, this now calls Preprocessor.evaluate from Preprocessor
```javascript
for (var key in runtimeDefines) {
                if (runtimeDefines.hasOwnProperty(key)) {
                    eval("var "+key+" = \""+addSlashes(""+runtimeDefines[key])+"\";");
                }
            }
```

And now it fail, in my case it failed because of the "!", or execute whatever you may injected there.

So you should filter process.env here and optionally make the extending with System Variables optional.

This can be a vulnerability too. The PATH variables can be set without privileges (under windows) and this may encounter in a privilege escalation.

And now excuse me. I'm in hurry to get back to my Linux machine again...

**Comment by STAH** [comment]
Please open issue on https://github.com/nashdot/Preprocessor.js.
Grunt task is based on it.
